### ISSUE TITLE
Compile failure on Debian buster

### ISSUE THREAD

**Issue by lizdodd** [rob-hills/rcphills-sma-bluetooth-dbabstraction#1]
Running 'make' on the downloaded code gives me 

```
gcc -lbluetooth -lcurl -lm -lmysqlclient -ggdb -Wall -o smatool hexdump.o sunlight.o smatool.o logging.o bluetooth.o db_mysql.o
/usr/bin/ld: smatool.o: in function `post_interval_data':
/home/liz/git/rcphills-sma-bluetooth-dbabstraction/smatool.c:1236: undefined reference to `db_row_int_data'
collect2: error: ld returned 1 exit status
make: *** [Makefile:22: smatool] Error 1

```
Any ideas?

**Comment by rob-hills** [comment]
Hi Liz,
The variable this error refers to "db_row_string_data" is defined in [db_interface.h](https://github.com/rob-hills/rcphills-sma-bluetooth-dbabstraction/blob/master/db_interface.h) line 106.

I suggest you first check that you have that file present in your /home/liz/git/rcphills-sma-bluetooth-dbabstraction/ folder.  If you do have that file, then maybe your compiler isn't including the header file, possibly a default option that's set differently?

Unfortunately, it's been quite a few years since I last looked at this project, my own binary has been working faultlessly and hasn't needed maintenance so I've not needed to rebuild it.

If you're not a C/C++ programmer yourself (as indeed I'm not) you might want to ask someone who regularly uses "make", I suspect there will be a simple solution to the problem of not including header files.

HTH,

Rob Hills
Waikiki, Western Australia

**Comment by lizdodd** [comment]
On Sun, 10 Nov 2019 12:42:28 +0000 (UTC)
Rob Hills <notifications@github.com> wrote:

> Hi Liz,
> The variable this error refers to "db_row_string_data" is defined in
> [db_interface.h](https://github.com/rob-hills/rcphills-sma-bluetooth-dbabstraction/blob/master/db_interface.h)
> line 106.
> 
> I suggest you first check that you have that file present in your
> /home/liz/git/rcphills-sma-bluetooth-dbabstraction/ folder.  If you
> do have that file, then maybe your compiler isn't including the
> header file, possibly a default option that's set differently?
> 
> Unfortunately, it's been quite a few years since I last looked at
> this project, my own binary has been working faultlessly and hasn't
> needed maintenance so I've not needed to rebuild it.
> 
> If you're not a C/C++ programmer yourself (as indeed I'm not) you
> might want to ask someone who regularly uses "make", I suspect there
> will be a simple solution to the problem of not including header
> files.
> 
> HTH,
> 
> Rob Hills
> Waikiki, Western Australia
> 

Thanks for replying.
I then headed off to the heathen centre called Melbourne, and let this
ride.
I found some code that would read the sma inverter, and then deleted
all the failed efforts from the computers I had been using. 
Unless I download it again I won't know why it couldn't find that
header, and it may work the next time instead.
As neither of us is likely to benefit from the exercise, I'll be lazy
and not complete the check


Liz

**Comment by rob-hills** [comment]
No easy way to check this so closing this issue as "Won't Fix"
